orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
  aws-ecs: circleci/aws-ecs@1.1.0
version: 2.1
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: ACCESS_KEY_ID
          aws-secret-access-key: SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          path: ./
          region: AWS_REGION
          repo: test-orbs-sample
          tag: 'latest'
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          aws-access-key-id: ACCESS_KEY_ID
          aws-secret-access-key: SECRET_ACCESS_KEY
          aws-region: '${AWS_REGION}'
          family: 'circleci-orbs-service'
          cluster-name: 'circleci-orbs-cluster'
          container-image-name-updates: 'container=circleci-orbs-service,tag=latest'
